<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $users = [
            //dokter
            [
                'name' => 'Dr. dr. H. Moch. Yunus, M.Kes.',
                'nip' => '196402221996011000',
                'email' => 'mochyunus@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. dr. Rias Gesang Kinanti, M.Kes.',
                'nip' => '196707161999032000',
                'email' => 'riasgesangkinanti@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Hartati Eko Wardani, M.Si.Med',
                'nip' => '197501182000032000',
                'email' => 'hartatiekowardani@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Agung Kurniawan, M.Kes',
                'nip' => '197401222010121000',
                'email' => 'agungkurniawan@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Sendhi Tristanti Puspitasari, M.Kes',
                'nip' => '198405282010122000',
                'email' => 'sendhitrisantipuspitasari@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Anindya Hapsari, M.Kes',
                'nip' => '198501292012122000',
                'email' => 'anindyahapsari@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Tisnalia Merdya Andyastanti, S.Ked, M.Kes',
                'nip' => '198703042014042000',
                'email' => 'tisnaliamerdyaandyastanti@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. dr. Dhian Kartikasari, S.Ked, MMRS, M.H.',
                'nip' => '202008198704202000',
                'email' => 'dhiankartikasari@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Erianto Fanani, S.Ked., M.KKK.',
                'nip' => '198308232015041000',
                'email' => 'eriantofanani@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Nanang Tri Wahyudi, Sp.K.O.',
                'nip' => '202010197809021000',
                'email' => 'nanangtriwahyudi@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Ardhiyanti Puspita Ratna, M.Biomed',
                'nip' => '202010198504182000',
                'email' => 'ardhiyantipuspitaratna@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Karina Nilasari, Sp.PK.',
                'nip' => '202109198109072000',
                'email' => 'karinanilasari@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Dina Fauziah, M.Sc.',
                'nip' => '202204199208062000',
                'email' => 'dinafauziah@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Anditri Weningtyas, M.Biomed.',
                'nip' => '202204199701122000',
                'email' => 'anditriweningtyas@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. dr. Amalia Tri Utami, S.Ked., M.Biomed.',
                'nip' => '202204199104112000',
                'email' => 'amaliatriutami@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Dennada Bagus Putra Perdana, Sp.KJ, M.H.',
                'nip' => '202204198705261000',
                'email' => 'dennadabagusputraperdana@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Editya Fukata, S.Ked, M.Biomed',
                'nip' => '202212199706051000',
                'email' => 'edityafukata@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Bimo Kusumo Bhirowo, Sp.An',
                'nip' => '202308199010121000',
                'email' => 'bimokusumobhirowo@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Dyta Loverita, Sp.OG.',
                'nip' => '202308198908272000',
                'email' => 'dytaloverita@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Lintang Widya Sishartami, M.Biomed',
                'nip' => '202212199503082000',
                'email' => 'lintangwidyasishartami@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Hilma Tsurayya Iftitahurroza, S.Ked., MHPE',
                'nip' => '202308199303192000',
                'email' => 'hilmatsurayyaiftitahurroza@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Andrew Halim, Sp.THT-KL, FICS',
                'nip' => '202302198704301000',
                'email' => 'andrewhalim@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Rokhmatul Asiyah, S.Ked., M.Biomed.',
                'nip' => '202304199202252000',
                'email' => 'rokhmatulasiyah@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Didiek Darmadi Tri Setyo, S.Ked, Sp.B.',
                'nip' => '202302198706231000',
                'email' => 'didiekdarmaditrisetyo@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Dewi Maharani, Sp.N., M.Biomed',
                'nip' => '202509198712312000',
                'email' => 'dewimaharani@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Zulfikar Ramadhan, M.H.',
                'nip' => '202501199602061000',
                'email' => 'zulfikarramadhan@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Kiky Martha Ariesaka, M.Biomed.',
                'nip' => '202308199603212000',
                'email' => 'kikymarthaariesaka@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Deka Miftalia Anugrah Putri, Sp. PA',
                'nip' => '202503199310182000',
                'email' => 'dekamiftaliaanugrahputri@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Syarah Nandya Dinnarwika, Sp.M.',
                'nip' => '202509199108302000',
                'email' => 'syarahnandyadinnarwika@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Dinda Rozita Maharani, Sp.D.V.E',
                'nip' => '202601199201292000',
                'email' => 'dindarozitamaharani@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Nurul Laili Nahlia, Sp.DV',
                'nip' => '202308199001142000',
                'email' => 'nurullailinahlia@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Andreas Budi Wijaya, M.Biomed, Sp.A',
                'nip' => '202304199106051000',
                'email' => 'andreasbudiwijaya@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Farid Eka Wahyu Endarto',
                'nip' => '198306092012121000',
                'email' => 'faridekawahyuendarto@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Ifa Mufida, MMRS.',
                'nip' => '198512232014042000',
                'email' => 'ifamufida@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'drg. Muslim Paranto Noor Asoffa',
                'nip' => '198401312014041000',
                'email' => 'muslimparantonoorasoffa@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'drg. Fardhian Dhiyawardhana',
                'nip' => '202501199510271000',
                'email' => 'fardhiandhiyawardhana@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'dr. Indira Pradita Rochim, S.Ked.',
                'nip' => '202501199804032000',
                'email' => 'indirapraditarochim@dokter.com',
                'password' => Hash::make('password123'),
                'role' => 'dokter',
                'email_verified_at' => now(),
            ],

            //perawat
            [
                'name' => 'Andriana Dyah Ratnawati, S.E..',
                'nip' => '198007222009102000',
                'email' => 'andrianadyahratnawati@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Tukul Wiyanto',
                'nip' => '196904302007011000',
                'email' => 'tukulwiyanto@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Yayuk Ratnawati, S.AP.',
                'nip' => '198201012009102000',
                'email' => 'yayukratnawati@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Lestari Handayani, S.Pd.',
                'nip' => '202210198808152000',
                'email' => 'lestarihandayani@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Aditya Yudha Pratama, S.Pd.',
                'nip' => '202210198912151000',
                'email' => 'adityayudhapratama@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Faradita Nindyasari, S.Si., M.Si.',
                'nip' => '202601199609042000',
                'email' => 'faraditanindyasari@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nenes Prastita, S.Si., M. Si.',
                'nip' => '202601199908142000',
                'email' => 'nenesprastita@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Erika Ayu Sylvianingrum, S.Kep., Ns.',
                'nip' => '202601199902192000',
                'email' => 'erikaayusylvianingrum@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Luthfi Syarifa Rasyidatu Hasnanda, S.Si.',
                'nip' => '202601199911192000',
                'email' => 'luthfisyarifarasyidatuhasnanda@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dimas Nur Ramadhani, S.Si., M.Si',
                'nip' => '202601199812061000',
                'email' => 'dimasnurramadhani@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nur Khalifah, A.Md.',
                'nip' => '199701202022032000',
                'email' => 'nurkhalifah@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Agung Cahyo Wibowo, S.Ak.',
                'nip' => '202210199204011000',
                'email' => 'agungcahyowibowo@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Yusuf Effendi, S.I.Pust.',
                'nip' => '202210197903231000',
                'email' => 'yusufeffendi@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Amelia Iradany, S.Kep., Ns., M.Biomed.',
                'nip' => '202308199007122000',
                'email' => 'ameliairadany@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Qory Tifani Rahmatika, S.Kep., Ns., M.Kep.',
                'nip' => '202204199310232000',
                'email' => 'qorytifanirahmatika@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. Nurma Afiani, S.Kep., Ns., M.Kep.',
                'nip' => '202206198606302000',
                'email' => 'nurmaafiani@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Eri Yanuar Akhmad Budi Sunaryo, S.Kep., Ns., M.NSc.',
                'nip' => '202206198701311000',
                'email' => 'eriyanuarakhmadbudisunaryo@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Yhenti Widjayanti, S.Kep., Ns., M.Kes.',
                'nip' => '202206198407222000',
                'email' => 'yhentiwidjayanti@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Ronal Surya Aditya, S.Kep., Ns., M.Kep.',
                'nip' => '202206199202131000',
                'email' => 'ronalsuryaaditya@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. Achmad Masfi, S.Kep., Ns., M.Kep.',
                'nip' => '202206198901161000',
                'email' => 'achmadmasfi@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nurul Evi, S.Kep, Ns., M.Kep, Sp.Kep.Mat',
                'nip' => '202207198209292000',
                'email' => 'nurulevi@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Muhammad Putra Ramadhan, S.Kep, Ns., M.Kep, Sp.Kep.M.B',
                'nip' => '202204199303111000',
                'email' => 'muhammadputraramadhan@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Shannastaniar Aisya Adif, S.Kep., Ns., M.S.',
                'nip' => '202508199503152000',
                'email' => 'shannastaniaraisyaadif@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Neni Fidya Santi, S.Kep., Ns., M.Kep., Ns.Sp.Kep.Mat.',
                'nip' => '202311198711292000',
                'email' => 'nenifidyasanti@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nafisah, S.Kep., Ns., M.Kep.',
                'nip' => '202507199702282000',
                'email' => 'nafisah@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nindi Kusuma Dewi, S.Keb., Bd., M.Keb.',
                'nip' => '202206199212232000',
                'email' => 'nindikusumadewi@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Elisa Danik Kurniawati, S.Tr.Keb., Bdn., M.Keb.',
                'nip' => '202204199609262000',
                'email' => 'elisadanikkurniawati@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Zumroh Hasanah, S.Keb, Bd., M.Kes',
                'nip' => '202206199106052000',
                'email' => 'zumrohhasanah@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nina Rini Suprobo, S.Keb., Bd., M.Keb.',
                'nip' => '202204199310282000',
                'email' => 'ninarinisuprobo@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dr. Dewi Ratna Sulistina, S.ST., S.Keb., Bdn., M.Keb.',
                'nip' => '202206198606222000',
                'email' => 'dewiratnasulistina@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Alifia Candra Puriastuti, S.Keb., Bd., M.Kes',
                'nip' => '202206199007132000',
                'email' => 'alifiacandrapuriastuti@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Rizqie Putri Novembriani, S.Keb, Bd., M.K.M.',
                'nip' => '202204199211192000',
                'email' => 'rizqieputrinovembriani@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Laras Putri Gamagitta, S.Keb, Bd., M.Keb',
                'nip' => '202204199406242000',
                'email' => 'larasputrigamagitta@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Dessy Amelia, S.Keb, Bd., M.Kes',
                'nip' => '202204199012012000',
                'email' => 'dessyamelia@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Winny Kirana Hasanah, S.Keb, Bd., M.K.M.',
                'nip' => '202211199612222000',
                'email' => 'winnykiranahasanah@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Khusnul Khotimah, A.MK.',
                'nip' => '197710132008102000',
                'email' => 'khusnulkhotimah@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Irwan Andrianto, S.AP',
                'nip' => '197710312007101000',
                'email' => 'irwanandrianto@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Keysha Amara Johar, S.M.',
                'nip' => '202508200206272000',
                'email' => 'keyshaamarajohar@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Imelda Tri Omega, S.Kep., Ners.',
                'nip' => '202601200003072000',
                'email' => 'imeldatriomega@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Nanang Rifai, S.Kep., Ners.',
                'nip' => '202210198705051000',
                'email' => 'nanangrifai@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Yudha Pratama, A.Md. RMIK, S.Kom.',
                'nip' => '202210198804231000',
                'email' => 'yudhapratama@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Odilia Isyanti Nursavitri, A.Md. Farm.',
                'nip' => '202601200107202000',
                'email' => 'odiliaisyantinursavitri@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Agus Triwiono',
                'nip' => '202210197908071000',
                'email' => 'agustriwiono@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Ahmad Widodo',
                'nip' => '202210197102231000',
                'email' => 'ahmadwidodo@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Wigi Wirya Wirama, A.Md.RMIK',
                'nip' => '202210199708271000',
                'email' => 'wigiwiryawirama@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Ardiansyah Ainur Fachrudin Waluyo, A.Md. Kep.',
                'nip' => '202408199710201000',
                'email' => 'ardiansyahainurfachrudinwaluyo@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'apt. Nisa Permatasari Wiyono, S.Farm.',
                'nip' => '202408199807112000',
                'email' => 'nisapermatasariwiyono@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Anisa Harum Istighfarin, S.Keb., Bd.',
                'nip' => '202408199510312000',
                'email' => 'anisaharumistighfarin@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Indana Tri Rahmawati, S.KM., M.Kes',
                'nip' => '202302199512142000',
                'email' => 'indanatrirahmawati@perawat.com',
                'password' => Hash::make('password123'),
                'role' => 'perawat',
                'email_verified_at' => now(),
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}
